# Generated by Django 2.0.6 on 2018-10-16 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='recipe',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='timeCook',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
