# Generated by Django 2.0.6 on 2018-10-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_auto_20181016_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
